//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.11 at 09:29:57 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.ukomp.rekrut.soap.checkvat;
